version: '3.7'

services:
    api: 
        build:
            context: ./back
            dockerfile: ./Dockerfile
        ports:
            - 8000:8000
        container_name: fs-afiliados-api
        depends_on:
            - db
        networks:
            - fs-afiliados
        env_file:
            - ./back/.env
        environment:
            ENVIRONMENT: development
        command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
      
    db:
        image: "postgres"
        env_file: 
            - ./back/.env
        container_name: fs-afiliados-db
        restart: always
        networks:
            - fs-afiliados

networks:
    fs-afiliados:
        driver: bridge

